FROM python:3.12

# Install only the runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libblas-dev \
    liblapack-dev \
    libfftw3-dev \
    libtool \
    gfortran && \
    rm -rf /var/lib/apt/lists/*

# Copy KIM API and model installation from builder
COPY --from=taisrc/kim /usr/local /usr/local

# Copy jaix from another base image
COPY --from=taisrc/jaix_base:latest /jaix /jaix

WORKDIR /jaix
RUN pip install pip-tools && \
    pip-compile --extra ase --output-file requirements.txt setup.py && \
    pip install --no-cache-dir --no-deps -r requirements.txt
RUN pip install --no-deps --no-cache-dir -e .[ase]

# Set working directory for testing
WORKDIR /tests

