FROM kim 

# Copy jaix from another base image
COPY --from=jaix_base /jaix /jaix
COPY --from=jaix_base /opt/jaix/ /usr/local

WORKDIR /jaix
RUN pip install pip-tools && \
    pip-compile --extra ase --output-file requirements.txt setup.py && \
    pip install --no-cache-dir --find-links=/wheels -r requirements.txt
RUN pip install --no-deps --no-cache-dir -e .[ase] 

# Set working directory for testing
WORKDIR /tests

