FROM python:3.12 AS cobi

# Set working directory
WORKDIR /cobi

# Copy only requirements first (for better caching if setup.py doesn't change often)
COPY cobi/pyproject.toml .
COPY cobi/requirements.txt .
COPY cobi/src src

RUN pip install --prefix=/opt/cobi -r requirements.txt
RUN pip install --prefix=/opt/cobi .

FROM python:3.12

COPY --from=cobi /opt/cobi/ /usr/local
COPY --from=jaix_base /jaix /jaix
COPY --from=jaix_base /opt/jaix/ /usr/local

WORKDIR /jaix

ARG EXTRAS
RUN pip install --no-cache-dir -e .${EXTRAS}

WORKDIR /tests


